name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: srivatsav-sai
          password: ${{ secrets.CALESPEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/srivatsav-sai/angularsite:arm64

      - name: Verify Docker image
        run: |
          echo "Listing pushed images"
          docker images ghcr.io/srivatsav-sai/angularsite:arm64
